### ISSUE TITLE
Recover the repository

### ISSUE THREAD

**Issue by steevanb** [phpsdk/middleware#5]
Hi,

It's been a while since last commit, do you think i can recover the repository?

I want to start a SDK project in PHP and `phpsdk` is a good name :)

**Comment by slavcodev** [comment]
Yes. I've sent an invite and can transfer ownership of this organization to you.

**Comment by steevanb** [comment]
Thanks, i've joined the organization

**Comment by slavcodev** [comment]
Awesome. 

You can remove this repository and create new one with clean history and feel free to remove me from org owners.

Good luck.
